### ISSUE TITLE
Code duplication computeAssignedVars

### ISSUE THREAD

**Issue by ibnyusuf** [vprover/rapid#3]
In `AnalysisPreComputation` and in `StaticAnalysisLemmas` we have a function `computeAssignedVars` both of which seem to do the same thing. We should remove one.

**Comment by PracticalMetal** [comment]
Hi, I would like to work on this. Can you suggest me ways to get started?

**Comment by ibnyusuf** [comment]
Thanks for your offer. This is a pretty straightforward code duplication issue. If you want to help, the steps to follow would be:

1. Create a fork
2. Replace all references to `StaticAnalysisLemmas::computeAssignedVars` with references to `AnalysisPreComputation::computeAssignedVars`.
3. Remove the now unused duplicate function
4. Make sure everything compiles
5. Create a pull request

**Comment by PracticalMetal** [comment]
Okay! I am working on it.

**Comment by mina1604** [comment]
The issue is resolved.
